# Generated by Django 3.2.8 on 2021-12-23 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_image_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='profile',
        ),
    ]
