# Generated by Django 3.2.8 on 2022-01-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='marital_state',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('U', 'Unmarried')], default='S', max_length=5),
        ),
    ]
